version : '3.7'

services:
    app:
        build:
            context: ./server
            args:
                BUILD_ENV: "${BUILD_ENV:-production}"
                HARL_BRANCH: "${HARL_BRANCH:-master}"
                GRAPHICS: "${GRAPHICS:-overcooked_graphics_v2.2.js}"
        environment: 
            FLASK_ENV: "${BUILD_ENV:-production}"
        ports:
            - "80:5000"
        
